import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';

// Initialize Gemini client
const ai = new GoogleGenAI({ apiKey });

export const restoreImage = async (
  base64Data: string, 
  mimeType: string,
  modelName: string = 'gemini-2.5-flash-image'
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please set the API_KEY environment variable.");
  }

  try {
    const prompt = `
      Act as a world-class photo restoration and enhancement AI.
      
      INPUT: An old, damaged, blurry, or low-quality photo.
      
      YOUR TASK: Transform this image into a pristine, HIGH-DEFINITION (4K) DSLR-quality photograph.
      
      STRICT GUIDELINES:
      1. EXTREME SHARPENING: Drastically improve clarity and resolution. Remove all blur, haze, and noise. 
         - Restore defined edges.
         - Hallucinate realistic high-frequency details (skin pores, hair strands, fabric texture) where missing.
      2. DAMAGE REPAIR: Seamlessly heal all cracks, scratches, tears, creases, and dust spots.
      3. VIBRANT COLOR: 
         - If B&W: Colorize with sophisticated, historically accurate, and natural colors.
         - If Color: Correct fading, fix white balance, and boost contrast/vibrancy to modern standards.
      4. IDENTITY PRESERVATION: enhance facial features (eyes, nose, mouth) to be sharp and distinct, but STRICTLY PRESERVE the person's original identity. Do not generate a generic face.
      
      Return ONLY the restored image data.
    `;

    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data,
            },
          },
        ],
      },
    });

    // Parse the response to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    
    if (!parts || parts.length === 0) {
      throw new Error("No content generated by Gemini.");
    }

    // Iterate to find the image part
    for (const part of parts) {
      if (part.inlineData && part.inlineData.data) {
        return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      }
    }
    
    // If text was returned instead
    const textPart = parts.find(p => p.text);
    if (textPart) {
      console.warn("Gemini returned text instead of image:", textPart.text);
      throw new Error("The model returned text instead of an image. Please try again.");
    }

    throw new Error("No image data found in the response.");

  } catch (error: any) {
    console.error("Gemini Restoration Error:", error);
    throw new Error(error.message || "Failed to restore image.");
  }
};